name: RavelDatapack
version: 1.0
main: com.connexal.raveldatapack.RavelDatapack
api-version: 1.19
depend: [EasyDatapack]

commands:
  raveldatapack:
    permission: raveldatapack.raveldatapack
    description: Ravel datapack command
  ravelschematic:
    permission: raveldatapack.ravelschematic
    description: Create schematics for the Ravel datapack
  ravelbiome:
    permission: raveldatapack.ravelbiome
    description: Get what biome you're currently in

permissions:
  raveldatapack.raveldatapack:
    description: Allows the player to use the Ravel datapack command
    default: true
  raveldatapack.ravelschematic:
    description: Allows the player to use the Ravel schematic command
    default: op
  raveldatapack.ravelbiome:
    description: Allows the player to use the Ravel biome command
    default: true