name: RavelDatapack
version: ${project.version}
main: com.connexal.raveldatapack.RavelDatapack
api-version: 1.17
softdepend: [floodgate]

commands:
  raveldatapack:
    permission: raveldatapack.raveldatapack
    description: Ravel datapack command
  ravelschematic:
    permission: raveldatapack.ravelschematic
    description: Reload the resource pack

permissions:
  raveldatapack.raveldatapack:
    description: Allows the player to use the Ravel datapack command
    default: true
  raveldatapack.ravelschematic:
    description: Allows the player to use the Ravel schematic command
    default: op